services:
  - type: web
    name: theralink-app
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    aptPackages:
      - ffmpeg
