"""Add subscription_type and group_id

Revision ID: 0dc02aadc659
Revises: 5e832c2250a8
Create Date: 2025-09-02 19:03:05.050366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc02aadc659'
down_revision = '5e832c2250a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('group_id', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('group_id')
        batch_op.drop_column('subscription_type')

    # ### end Alembic commands ###
